-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 15:04:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema yobson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yobson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yobson` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `yobson` ;

-- -----------------------------------------------------
-- Table `yobson`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yobson`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur` VARCHAR(25) CHARACTER SET 'utf8mb3' NOT NULL,
  `prenom` VARCHAR(75) NOT NULL,
  `nom` VARCHAR(75) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `adresse_ip` VARCHAR(255) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NULL DEFAULT NULL,
  `langue` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
